name: Print File Content CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened]

jobs:
  build_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print Hello World
        run: |
          cat hello_world.txt